const express = require('express');
const mongoose = require('mongoose')
const keys = require('./config/keys')

// import the model before you rerquire the passort. we use models in passport
require('./models/User')
// import the passport authentication code
require('./services/passport')


//connect to mongoDB with our key (this has our username and password to grant us access to the DB)
mongoose.connect(keys.mongoURI)

// call express to create an applciation that will handle our HTTP requests (ie: GET, USE, POST, UPDATE)
const app = express();


// require the authRoutes file, but the authRoutes file is a returned function with an input. That input is our app file generated by express. This makes sure that we can assign the routes from authRoutes correctly to the same 'app' generated in our server.js file
require('./routes/authRoutes')(app)

// for deployment
// if the process.env (core node module about the environment of the app) has a PORT to listen to (which would be assigned by a site like heroku), then listen to that. if not. the app will listen on localhost:5000
const PORT = process.env.PORT || 5000;
app.listen(PORT)